### ISSUE TITLE
Release to Maven central

### ISSUE THREAD

**Issue by alaisi** [tlbdk/copybook4java#1]
The project is currently not consumable as a dependency. Alpha release is better than no release. :)

**Comment by tlbdk** [comment]
Hi Antti,

I looked a bit into it and to get it into maven I need to create a signed
build artifact and have that work with Travis that I'm currently using for
build the project. I have not had any free time neither at work or a home
lately. But the coming weekend I should have some time.

Regards Troels

**Comment by alaisi** [comment]
Hi,

thanks for the reply. 

You most likely already found this but just in case: http://central.sonatype.org/pages/ossrh-guide.html . Regarding the maven configuration, the simplest way is to use org.sonatype.oss:oss-parent (even though it is deprecated) as parent pom and then you only need to set up the pgp keys and run mvn release:prepare/perform.

**Comment by tlbdk** [comment]
It has been released now:
http://search.maven.org/#search%7Cga%7C1%7Ccopybook4java
