### ISSUE TITLE
Serialization of uninitialized nested structures fails

### ISSUE THREAD

**Issue by madsskagen** [tlbdk/copybook4java#8]
When a nested structure (BigInteger etc.) is used with no default value explicitly defined, serialization fails when using CopyBookSerializer.serialize(..)

Example:

```
       07 SOME-ACCOUNT PIC 9(10).
```

Translates to 

```
    @CopyBookLine("07 SOME-ACCOUNT PIC 9(10).")
    private BigInteger someAccount;
```

Should translate to

```
    @CopyBookLine("07 SOME-ACCOUNT PIC 9(10).")
    private BigInteger someAccount= new BigInteger("0");
```

**Comment by tlbdk** [comment]
Added config option on CopyBook to handle this, by default it will no do the expected and use a sane default value.
